const algoliasearch = require('algoliasearch');
const client = algoliasearch('0EZXUQCHB2', '11ce40c14dd66f68b424520376ae529f');
const index = client.initIndex('www');

// Import the JSON file generated by Hugo
const jsonIndex = require('./public/index.json');

index.addObjects(jsonIndex, (err, content) => {
  console.log(content);
});
