const algoliasearch = require('algoliasearch');
const client = algoliasearch('0EZXUQCHB2', process.env.ALGOLIA_API_SECRET);
const index = client.initIndex('www');

// Import the JSON file generated by Hugo
const jsonIndex = require('./public/index.json');

index.addObjects(jsonIndex, (err, content) => {
  console.log(content);
});
