<?php /*
Template Name: Customer Page
*/ ?>

<?php get_header(getHeaderTemplateName()) ?>

    <div class="customer-page_head">
      <div class="grid-container"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/customer-page/imgs/head.svg" alt="">
        <h1>Metricly Success Stories</h1>
        <p>DevOps teams around the world rely on Metricly every day to have happier AWS environments</p>
      </div>
    </div>
    <div class="stories">
      <div class="grid-container -thin">
        <div class="stories_subwrap">
          <div class="stories_story"><img class="stories_story_img" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/customer-page/imgs/story1.jpg" alt="">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/customer-page/logos/parsely@2x.png" alt=""></div>
              <h4 class="stories_story_main_title"><b>How Parse.ly Leverages Metricly to Detect Performance Problems Early</b> </h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Download PDF</a>
            </div>
          </div>
          <div class="stories_story -with-review">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
              <h4 class="stories_story_main_title"><b>Joseph T.</b> DevOps Assistant</h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Read Full Review</a>
              <div class="stories_story_review">
                <div class="stories_story_main_img -review-img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
                <p class="stories_story_review_summary">Experience has been great. They put a lot of effort into developing a great and useful product.</p>
                <ul class="stories_story_review_score"> 
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Easy of Use</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Features & Functionality</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Customer Support</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Value for Money</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                </ul><a class="stories_story_main_link -review-link" href="#">Read Full Review</a>
              </div>
            </div>
          </div>
          <div class="stories_story -with-review">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
              <h4 class="stories_story_main_title"><b>Joseph T.</b> DevOps Assistant</h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Read Full Review</a>
              <div class="stories_story_review">
                <div class="stories_story_main_img -review-img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
                <p class="stories_story_review_summary">Experience has been great. They put a lot of effort into developing a great and useful product.</p>
                <ul class="stories_story_review_score"> 
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Easy of Use</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Features & Functionality</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Customer Support</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Value for Money</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                </ul><a class="stories_story_main_link -review-link" href="#">Read Full Review</a>
              </div>
            </div>
          </div>
          <div class="stories_story">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/customer-page/logos/trice@2x.png" alt=""></div>
              <h4 class="stories_story_main_title"><b>How Parse.ly Leverages Metricly to Detect Performance Problems Early</b> </h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Read Case Study	</a>
            </div><img class="stories_story_img" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/customer-page/imgs/story2.jpg" alt="">
          </div>
        </div>
      </div>
    </div>
    <div class="customer-page_share">
      <div class="grid-container">
        <h3>Share with us</h3>
        <h2>Your Metricly Story</h2>
        <p>
           It's in the name, Metricly; plethora of metrics available with lots of customization 
          	for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set.
        </p><a href="#">Learn More</a>
      </div>
    </div>
    <div class="stories">
      <div class="grid-container -thin">
        <div class="stories_subwrap">
          <div class="stories_story -with-review">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
              <h4 class="stories_story_main_title"><b>Joseph T.</b> DevOps Assistant</h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Read Full Review</a>
              <div class="stories_story_review">
                <div class="stories_story_main_img -review-img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
                <p class="stories_story_review_summary">Experience has been great. They put a lot of effort into developing a great and useful product.</p>
                <ul class="stories_story_review_score"> 
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Easy of Use</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Features & Functionality</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Customer Support</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Value for Money</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                </ul><a class="stories_story_main_link -review-link" href="#">Read Full Review</a>
              </div>
            </div>
          </div>
          <div class="stories_story -with-review">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
              <h4 class="stories_story_main_title"><b>Joseph T.</b> DevOps Assistant</h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Read Full Review</a>
              <div class="stories_story_review">
                <div class="stories_story_main_img -review-img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
                <p class="stories_story_review_summary">Experience has been great. They put a lot of effort into developing a great and useful product.</p>
                <ul class="stories_story_review_score"> 
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Easy of Use</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Features & Functionality</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Customer Support</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Value for Money</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                </ul><a class="stories_story_main_link -review-link" href="#">Read Full Review</a>
              </div>
            </div>
          </div>
          <div class="stories_story -with-review">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
              <h4 class="stories_story_main_title"><b>Joseph T.</b> DevOps Assistant</h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Read Full Review</a>
              <div class="stories_story_review">
                <div class="stories_story_main_img -review-img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
                <p class="stories_story_review_summary">Experience has been great. They put a lot of effort into developing a great and useful product.</p>
                <ul class="stories_story_review_score"> 
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Easy of Use</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Features & Functionality</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Customer Support</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Value for Money</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                </ul><a class="stories_story_main_link -review-link" href="#">Read Full Review</a>
              </div>
            </div>
          </div>
          <div class="stories_story -with-review">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
              <h4 class="stories_story_main_title"><b>Joseph T.</b> DevOps Assistant</h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Read Full Review</a>
              <div class="stories_story_review">
                <div class="stories_story_main_img -review-img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
                <p class="stories_story_review_summary">Experience has been great. They put a lot of effort into developing a great and useful product.</p>
                <ul class="stories_story_review_score"> 
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Easy of Use</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Features & Functionality</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Customer Support</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Value for Money</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                </ul><a class="stories_story_main_link -review-link" href="#">Read Full Review</a>
              </div>
            </div>
          </div>
          <div class="stories_story -with-review">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
              <h4 class="stories_story_main_title"><b>Joseph T.</b> DevOps Assistant</h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Read Full Review</a>
              <div class="stories_story_review">
                <div class="stories_story_main_img -review-img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
                <p class="stories_story_review_summary">Experience has been great. They put a lot of effort into developing a great and useful product.</p>
                <ul class="stories_story_review_score"> 
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Easy of Use</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Features & Functionality</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Customer Support</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Value for Money</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                </ul><a class="stories_story_main_link -review-link" href="#">Read Full Review</a>
              </div>
            </div>
          </div>
          <div class="stories_story -with-review">
            <div class="stories_story_main">
              <div class="stories_story_main_img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
              <h4 class="stories_story_main_title"><b>Joseph T.</b> DevOps Assistant</h4>
              <p class="stories_story_main_summary">It's in the name, Metricly; plethora of metrics available with lots of customization for different dashboards and alerts. It is able to pick up and alert on historical data which is nice, since alerting on set thresholds isn't always helpful. Although we don't use the cost analysis tools often, I can see it pay for the cost of Metricly itself for other customers.</p><a class="stories_story_main_link" href="#">Read Full Review</a>
              <div class="stories_story_review">
                <div class="stories_story_main_img -review-img"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/lines.svg" alt=""></div>
                <p class="stories_story_review_summary">Experience has been great. They put a lot of effort into developing a great and useful product.</p>
                <ul class="stories_story_review_score"> 
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Easy of Use</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Features & Functionality</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Customer Support</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                  <li class="stories_story_review_score_item"><span class="stories_story_review_score_item_label">Value for Money</span>
                    <div class="stories_story_review_score_item_stars"><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star -active" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""><img class="stories_story_review_score_item_stars_star" src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/stories/icons/star.svg" alt=""></div>
                  </li>
                </ul><a class="stories_story_main_link -review-link" href="#">Read Full Review</a>
              </div>
            </div>
          </div>
        </div>
      </div><a class="stories_link-more">Show More	</a>
    </div>
<div class="start-section">
  <div class="grid-container"><img src="https://s3-us-west-2.amazonaws.com/com-netuitive-app-usw2-public/wp-content/uploads/assets/customer-page/imgs/start.svg" alt="">
    <div class="start-section_subwrap">
      <h2>Start monitoring with Metricly today</h2>
      <p>
         It's in the name, Metricly; plethora of metrics available with lots of customization 
        for different dashboards and alerts. It is able to pick up and alert.
      </p><a href="#">Get Started Free</a>
    </div>
  </div>
</div>

<?php get_footer(); ?>